# These are supported funding model platforms

github: [jeancx, odirlon]
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
buy_me_a_coffee: jeancf
thanks_dev: # Replace with a single thanks.dev username
